"""Added all tables

Revision ID: 9e0cf9b0ac21
Revises: ae1027a6acf
Create Date: 2022-10-27 21:59:02.823778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0cf9b0ac21'
down_revision = 'ae1027a6acf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
